-- 코드를 작성해주세요  
# 부모의 희귀도가 RARE인 자식 아이템을 출력
SELECT B.ITEM_ID, A.ITEM_NAME, A.RARITY 
FROM ITEM_INFO AS A INNER JOIN ITEM_TREE AS B ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY B.ITEM_ID DESC