-- 코드를 작성해주세요
-- YEAR, YEAR_DEV, ID 출력
-- YEAR_DEV : 분화된 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
    ,(SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE YEAR(DIFFERENTIATION_DATE) = YEAR) - SIZE_OF_COLONY AS YEAR_DEV
    , ID 
FROM ECOLI_DATA 
ORDER BY YEAR, YEAR_DEV