-- 코드를 작성해주세요
SELECT SUM(C.SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL 
# SELECT *
FROM HR_DEPARTMENT AS A INNER JOIN HR_EMPLOYEES AS B ON A.DEPT_ID = B.DEPT_ID
INNER JOIN HR_GRADE AS C ON B.EMP_NO = C.EMP_NO
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1