-- 코드를 입력하세요
SELECT A.CATEGORY AS CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A INNER JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
WHERE 
    DATE_FORMAT(B.SALES_DATE,'%Y-%m-%d') >= DATE_FORMAT('2022-01-01','%Y-%m-%d') 
    AND 
    DATE_FORMAT(B.SALES_DATE,'%Y-%m-%d') < DATE_FORMAT('2022-02-01','%Y-%m-%d') 
    
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY